= el-CICD Charts
:toc:

== Overview

The el-CICD Charts are a collection of charts that implement an all-in-one solution to Helm Charts for Kubernetes resources and beyond, removing the need to write new charts, and instead allowing developers to focus on deployments across multiple deployments with a minimum of code.

== Features

The el-CICD Charts offer the following features:

=== Parameters in Values Files
el-CICD supports defining variables and parameters **_inside_** values files.

NOTE: el-CICD variables can only be used with el-CICD templates.  There are other ways to leverage the el-CICD charts for Helm templates that are not part of the el-CICD Chart template framework.  See <<Use cases>> for more information.

=== Profiles

el-CICD Chart support the concept of one or more profiles during rendering.  Profiles can influence the values of variables within the values files, as well as whether templates are rendered or not.

=== Easily extensible template framework

el-CICD supports adding new Custom Resource Definitions for use in the framework.  Kubernetes resources to support application and batch deployments are already built in, including a template for generating a `kustomization.yaml`.  If your own CRD's need to be supported, then  adding them is as easy `kubectl explain --recursive` and small bit of elbow grease.

TIP: It is **strongly** suggested that all CRD's added to the el-CICD framework be complete; i.e. include every key in the resource definition.

=== Automatically generate projected volumes for your pods based on selectors

el-CICD will collect ConfigMaps and Secrets based on a collection of selectors and generate projected volumes and mounts based on simple expressions.

=== Resource cloning built in

Ever needed to copy a common ConfigMap or Secret (or any resource) from one namespace to another?  Or wished to use a deployed resource similar to the prototype pattern across numerous namepsaces?  el-CICD Chart has this functionality built.  Name the source and destination namespaces along with the resource, and el-CICD Chart will create copies of those resources under the new chart based on already deployed resources.

=== Debugging features built in

el-CICD Chart comes with a number of helper settings for generating output to help with debugging; e.g. If you use a number of different values files, ever wish to quickly see what Helm calculated were the final values to render your chart?  el-CICD has flags to easily and quickly output these settings.

== Benefits

The following benefits are gained by including the el-CICD Chart in your CICD process.

=== Easier to support SDLC workflows with profile-based deployments

Helm was designed to be a package manager, similar nin scope to `dnf`, `apt`, or Microsoft

=== No need to write your own charts

Helm charts are code, and writing your own means bugs and QA on top of design and implementation.  It's a lot of effort when the real goal is deploying your application, not writing, testing, and debugging deployment scripts.

=== Easier to debug

=== Easier for developer's to learn and understand

=== Easier and more straightforward to extend

== Reference

== Use cases

== Licensing

el-CICD is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful, but **WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE**.  See the GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License along with this library; if not, write to

```
    The Free Software Foundation, Inc.
    51 Franklin Street
    Fifth Floor
    Boston, MA
        02110-1301
```

This document is licensed under the [Creative Commons Attribution 4.0 International License](https://creativecommons.org/licenses/by/4.0/legalcode). To view a copy of this license, visit

http://creativecommons.org/licenses/by/4.0/

or send a letter to

```
  Creative Commons
  PO Box 1866
  Mountain View, CA
      94042, USA.
```

---

This document is part of the el-CICD project, a complete CICD framework solution for for cloud deployments on Kubernetes

Copyright &#169; {localyear} Evan "Hippy" Slatis
email: hippyod+elcicd -at- gmail -dot- com