name:  asciidoc-tutorial-renderer

on:
  push:
    branches:
    - main
    paths:
    - 'docs/tutorial/**'

  pull_request_target:
    branches:
    - main
    paths:
    - 'docs/tutorial/**'
    types:
      - closed

  workflow_dispatch:

jobs:
  render_asciidoc:
    runs-on: ubuntu-latest
    name: Render Asciidoc
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: gh-pages

    - name: Configure Git
      run: |
        git merge main
        git config --global user.name "${{ github.repository_owner }}"
        git config --global user.email "${{ github.repository_owner }}@donotreply.org"

    - name: Build HTML
      uses: tonynv/asciidoctor-action@master
      with:
        program: "asciidoctor -D ./docs/tutorial -w -t docs/tutorial/tutorial.adoc"

    - name: Add and commit
      run: |
        git add ./docs/tutorial/tutorial.html
        git commit -m "generated tutorial.html"
        git push
